### ISSUE TITLE
Reference Material Values Relationships

### ISSUE THREAD

**Issue by marioscience** [UCHIC/ODM2Sensor#103]
In Calibrations Details. To show the Reference Material information I am using the relationship through CalibrationActions->CalibrationStandards->ReferenceMaterial and I am showing all ReferenceMaterialValues that are related to those ReferenceMaterials in the table. Is this correct or should I go through CalibrationActions->InstrumenOutputVariables->Variables->ReferenceMaterialValues->ReferenceMaterials?

I know we have discussed this before but I still get confused with what should be shown there.

**Comment by AmberSJones** [comment]
The direction in which you are querying the reference material information is correct. However, instead of displaying ALL ReferenceMaterialValues related to a ReferenceMaterial, you need to implement a check on the InstrumentOutputVariable in the CalibrationActions entity. This should correspond to the InstrumentOutputVariableID -> VariableID that is contained in ReferenceMaterialValues. So, the only ReferenceMaterialValue that is displayed is the one associated with that CalibrationAction. 

Let me know if that makes sense?

**Comment by marioscience** [comment]
That makes sense. I will make sure to do the check on the VariableID through InstrumentOutputVariableID.
