### ISSUE TITLE
Editing a site visit causes issues

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#231]
I created a site visit with a number of nested actions. When I tried to edit the site visit by simply adding to the action descriptions and saving, I get 500 - internal server error. In reviewing the site visit - only the first action that I created is retained.

![image](https://user-images.githubusercontent.com/5023186/34800355-8f677c3c-f620-11e7-8d91-abe810a09b62.png)

**Comment by Elijahwalkerwest** [comment]
Working on this. It's looking like there's an issue with its interaction with the database somehow, rather than explicitly in the code. The error for this specific issue seems to be when it calls delete on a result, it gives Invalid object name 'ODM2.sensordatainterface_measurementresult

Doing some investigating it looks like quite a few of these issues are stemming from the same place, I've been trying to find the cause.

**Comment by Elijahwalkerwest** [comment]
Looks like the MeasurementResult Model was messed up, and was causing 500 errors whenever trying to delete a result anywhere on the site. Fixed and deployed.

**Comment by AmberSJones** [comment]
This appears to be addressed. Closing.
