### ISSUE TITLE
Unable to create calibration standard

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/ODM2Sensor#241]
I attempt to create a calibration standard. I get an error. In this case, the entry was not actually created.
![image](https://user-images.githubusercontent.com/5023186/34801607-d39f3a6a-f626-11e7-861a-d01a7ad4fdda.png)

**Comment by Elijahwalkerwest** [comment]
Fixed, KIND OF. 

You can now create calibration standards, but datatables is throwing an error, but not affecting the creation. Working on that now.

**Comment by Elijahwalkerwest** [comment]
The error is due to there being a ghost entry in Calibration standards. Once I sync back to the clean DB this shouldn't be a problem. Tested creating standards in different ways, was unable to replicate creating a ghost standard. It must have been created when I was messing around with the initial fix.

**Comment by AmberSJones** [comment]
Closing - assuming the error being thrown will be handled.
